AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  AWS Lambda SAM Stack for GitHub integration (Production)

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: python3.11

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "aws-lambda-github-sam-stack-${Environment}-ExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ListBucketsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "aws-lambda-github-sam-stack-${Environment}"
      Handler: lambda_function.lambda_handler
      CodeUri: ./src
      Role: !GetAtt LambdaExecutionRole.Arn
      Description: "List Buckets Lambda Function"
      AutoPublishAlias: live
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

Outputs:

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref ListBucketsFunction

  LambdaFunctionArn:
    Description: ARN of the Lambda function alias
    Value: !GetAtt ListBucketsFunction.Arn

  LambdaFunctionAlias:
    Description: Alias pointing to latest Lambda version
    Value: !Ref ListBucketsFunction.LiveAlias
