AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for GitHub Lambda deployment (Production-ready)

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 128

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "aws-lambda-github-sam-${Environment}-exec-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ListBucketsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "aws-lambda-github-sam-${Environment}-ListBucketsFunction"
      Handler: lambda_function.lambda_handler
      CodeUri: ./src
      Role: !GetAtt LambdaExecutionRole.Arn
      AutoPublishAlias: Live
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

Outputs:

  ListBucketsFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ListBucketsFunction.Arn

  ListBucketsFunctionVersion:
    Description: Lambda Function Version
    Value: !GetAtt ListBucketsFunction.Version

  ListBucketsFunctionLiveAliasArn:
    Description: Lambda Function Live Alias ARN
    Value: !GetAtt ListBucketsFunction.Live.Arn
